//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        public int idProdukt { get; set; }
        public string nazwa { get; set; }
        public string kolor { get; set; }
        public string rozmiar { get; set; }
        public Nullable<int> ilosc { get; set; }
        public Nullable<int> cena { get; set; }
        public Nullable<int> ZdjecieidZdjecie { get; set; }
        public Nullable<int> KategoriaidKategoria { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        public virtual Zdjecie Zdjecie { get; set; }
    }
}
